
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.auth0.example: TRACE

# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 5QJWBGDaRFSV1cnmcYC6dcFPKOgBut0v
            client-secret: cj8P8Zrlp02GhXcjFttIjTKeleocNSyeGD7yhbBhjCtUtlagJOd8mGM_GOC2MX6d
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-go7ud01i.eu.auth0.com/